### ISSUE TITLE
generate c bug by daffodil

### ISSUE THREAD

**Issue by sucof** [kenballus/http-fuzzing#1]
hi, kenballus, when I use daffodil to generate c files, there is a bug as show below:

`~/http-fuzzing/http-parser$ make
"/home/test/apache-daffodil-3.3.0-bin/bin/daffodil" generate c --schema "http1_1.dfdl.xsd"

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!   An unexpected exception occurred. This is a bug!   !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

 Please report this bug and help us fix it:

  https://daffodil.apache.org/community/#issue-tracker

 Please include the following exception, the command you
 ran, and any input, schema, or tdml files used that led
 to this bug.

Schema Definition Error: PrimType string is not supported in C code generator.
Schema context: method Location line 94 column 8 in file:/home/test/http-fuzzing/http-parser/http1_1.dfdl.xsd
	at org.apache.daffodil.dsom.ImplementsThrowsSDE.SDE(SDE.scala:179)
	at org.apache.daffodil.dsom.ImplementsThrowsSDE.SDE$(SDE.scala:178)
	at org.apache.daffodil.dsom.LocalElementDeclBase.SDE(LocalElementDecl.scala:25)
	at org.apache.daffodil.runtime2.generators.CodeGeneratorState.getPrimType(CodeGeneratorState.scala:517)
	at org.apache.daffodil.runtime2.generators.CodeGeneratorState.addFieldDeclaration(CodeGeneratorState.scala:572)
	at org.apache.daffodil.runtime2.generators.ElementParseAndUnspecifiedLengthCodeGenerator.$anonfun$elementParseAndUnspecifiedLengthGenerateCode$1(ElementParseAndUnspecifiedLengthCodeGenerator.scala:50)
	at org.apache.daffodil.runtime2.generators.ElementParseAndUnspecifiedLengthCodeGenerator.$anonfun$elementParseAndUnspecifiedLengthGenerateCode$1$adapted(ElementParseAndUnspecifiedLengthCodeGenerator.scala:45)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.daffodil.runtime2.generators.ElementParseAndUnspecifiedLengthCodeGenerator.elementParseAndUnspecifiedLengthGenerateCode(ElementParseAndUnspecifiedLengthCodeGenerator.scala:45)
	at org.apache.daffodil.runtime2.generators.ElementParseAndUnspecifiedLengthCodeGenerator.elementParseAndUnspecifiedLengthGenerateCode$(ElementParseAndUnspecifiedLengthCodeGenerator.scala:26)
	at org.apache.daffodil.runtime2.Runtime2CodeGenerator$.elementParseAndUnspecifiedLengthGenerateCode(Runtime2CodeGenerator.scala:52)
	at org.apache.daffodil.runtime2.Runtime2CodeGenerator$.generateCode(Runtime2CodeGenerator.scala:73)
	at org.apache.daffodil.runtime2.generators.ElementParseAndUnspecifiedLengthCodeGenerator.$anonfun$elementParseAndUnspecifiedLengthGenerateCode$1(ElementParseAndUnspecifiedLengthCodeGenerator.scala:51)
	at org.apache.daffodil.runtime2.generators.ElementParseAndUnspecifiedLengthCodeGenerator.$anonfun$elementParseAndUnspecifiedLengthGenerateCode$1$adapted(ElementParseAndUnspecifiedLengthCodeGenerator.scala:45)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.apache.daffodil.runtime2.generators.ElementParseAndUnspecifiedLengthCodeGenerator.elementParseAndUnspecifiedLengthGenerateCode(ElementParseAndUnspecifiedLengthCodeGenerator.scala:45)
	at org.apache.daffodil.runtime2.generators.ElementParseAndUnspecifiedLengthCodeGenerator.elementParseAndUnspecifiedLengthGenerateCode$(ElementParseAndUnspecifiedLengthCodeGenerator.scala:26)
	at org.apache.daffodil.runtime2.Runtime2CodeGenerator$.elementParseAndUnspecifiedLengthGenerateCode(Runtime2CodeGenerator.scala:52)
	at org.apache.daffodil.runtime2.Runtime2CodeGenerator$.generateCode(Runtime2CodeGenerator.scala:73)
	at org.apache.daffodil.runtime2.CodeGenerator.generateCode(CodeGenerator.scala:88)
	at org.apache.daffodil.Main$.$anonfun$run$42(Main.scala:1381)
	at org.apache.daffodil.util.Timer$.getTimeResult(Timer.scala:78)
	at org.apache.daffodil.util.Timer$.getResult(Timer.scala:37)
	at org.apache.daffodil.Main$.run(Main.scala:1381)
	at org.apache.daffodil.Main$.main(Main.scala:1514)
	at org.apache.daffodil.Main.main(Main.scala)
make: *** [Makefile:8: c] Error 4
`

**Comment by kenballus** [comment]
This is a daffodil problem; the C backend can't do strings yet, but hopefully pretty soon that capability will be added.

**Comment by sucof** [comment]
So is there a temporary solution now?

**Comment by kenballus** [comment]
No. There will not be support for strings in the generated C code until daffodil adds string support to their C code generator.
